import fs from 'node:fs'
import path from 'node:path'
import { fileURLToPath } from 'node:url'
import {
  chapterSidebarTitle,
  moduleChapterNumber,
  cleanLessonMarkdown,
} from './course/chapters.mjs'
import {
  LESSON_CATALOG,
} from './course/lesson-catalog.mjs'

const root = path.resolve(path.dirname(fileURLToPath(import.meta.url)), '..')
const srcCourseRoot = path.join(root, 'course')
const websiteCourseRoot = path.join(root, 'website', 'course')
const vitepressDir = path.join(root, 'website', '.vitepress')
const structurePath = path.join(srcCourseRoot, 'structure.json')
const COURSE_ROUTE = '/course'

function loadStructure() {
  if (!fs.existsSync(structurePath)) {
    return null
  }
  return JSON.parse(fs.readFileSync(structurePath, 'utf8'))
}

function copyDir(src, dest) {
  fs.mkdirSync(dest, { recursive: true })
  for (const entry of fs.readdirSync(src, { withFileTypes: true })) {
    if (entry.name === 'structure.json') {
      continue
    }
    const srcPath = path.join(src, entry.name)
    const destPath = path.join(dest, entry.name)
    if (entry.isDirectory()) {
      copyDir(srcPath, destPath)
    } else if (entry.name.endsWith('.md')) {
      const raw = fs.readFileSync(srcPath, 'utf8')
      const out = entry.name === 'index.md' ? raw : cleanLessonMarkdown(raw)
      fs.writeFileSync(destPath, out, 'utf8')
    }
  }
}

function readMdMeta(filePath) {
  const raw = fs.readFileSync(filePath, 'utf8')
  const fm = raw.match(/^---\r?\n([\s\S]*?)\r?\n---/)
  if (fm) {
    const titleMatch = fm[1].match(/^title:\s*(?:"([^"]*)"|'([^']*)'|(.+))$/m)
    if (titleMatch) {
      return { title: (titleMatch[1] ?? titleMatch[2] ?? titleMatch[3]?.trim()) || '' }
    }
  }

  const h1 = raw.match(/^#\s+(.+)$/m)
  return { title: h1?.[1]?.trim() ?? path.basename(filePath, '.md') }
}

function loadModule(dir, shortTitle) {
  const moduleDir = path.join(srcCourseRoot, dir)
  if (!fs.existsSync(moduleDir)) {
    return null
  }

  const indexPath = path.join(moduleDir, 'index.md')
  const title = shortTitle || (fs.existsSync(indexPath) ? readMdMeta(indexPath).title : dir)

  const lessons = fs
    .readdirSync(moduleDir)
    .filter((f) => f.endsWith('.md') && f !== 'index.md')
    .sort((a, b) => a.localeCompare(b, 'en', { numeric: true }))
    .map((file) => {
      const slug = file.replace(/\.md$/, '')
      const relKey = `${dir}/${file}`
      const catalogTitle = LESSON_CATALOG[relKey]
      const meta = readMdMeta(path.join(moduleDir, file))
      const title = catalogTitle || meta.title
      return {
        slug,
        title,
        sidebar: title,
      }
    })

  return { dir, title, lessons }
}

function buildCourseTree(structure) {
  return {
    parts: structure.parts.map((part) => ({
      ...part,
      modules: part.modules.map((mod) => loadModule(mod.dir, mod.short)).filter(Boolean),
    })),
  }
}

function lessonSidebarItem(mod, lesson) {
  return {
    text: lesson.sidebar || lesson.title,
    link: `${COURSE_ROUTE}/${mod.dir}/${lesson.slug}`,
  }
}

function moduleShortTitle(structure, dir) {
  for (const part of structure.parts) {
    const mod = part.modules.find((m) => m.dir === dir)
    if (mod) return mod.short
  }
  return dir
}

function collectModulesInOrder(tree) {
  const modules = []
  for (const part of tree.parts) {
    for (const mod of part.modules) {
      modules.push(mod)
    }
  }
  return modules
}

/** 侧栏两级：章（一级）→ 课时（二级） */
function buildSidebar(tree, structure) {
  return collectModulesInOrder(tree).map((mod) => {
    const chapterNum = moduleChapterNumber(mod.dir)
    const short = moduleShortTitle(structure, mod.dir) || mod.title
    return {
      text: chapterSidebarTitle(chapterNum, short),
      collapsed: chapterNum !== 1,
      items: mod.lessons.map((lesson) => lessonSidebarItem(mod, lesson)),
    }
  })
}

function writeSidebarModule(sidebar) {
  const content = `// Auto-generated by scripts/sync-course.mjs — do not edit
export default ${JSON.stringify(sidebar, null, 2)}
`
  fs.mkdirSync(vitepressDir, { recursive: true })
  fs.writeFileSync(path.join(vitepressDir, 'sidebar.course.mjs'), content, 'utf8')
}

function countMarkdownFiles(dir) {
  let count = 0
  for (const entry of fs.readdirSync(dir, { withFileTypes: true })) {
    const full = path.join(dir, entry.name)
    if (entry.isDirectory()) {
      count += countMarkdownFiles(full)
    } else if (entry.name.endsWith('.md') && entry.name !== 'structure.json') {
      count++
    }
  }
  return count
}

function main() {
  if (!fs.existsSync(srcCourseRoot)) {
    console.warn('No course/ at repo root — skip course sync.')
    return
  }

  const structure = loadStructure()
  if (!structure) {
    console.warn('Missing course/structure.json — skip course sync.')
    return
  }

  const tree = buildCourseTree(structure)
  fs.mkdirSync(vitepressDir, { recursive: true })

  if (fs.existsSync(websiteCourseRoot)) {
    fs.rmSync(websiteCourseRoot, { recursive: true, force: true })
  }

  copyDir(srcCourseRoot, websiteCourseRoot)
  writeSidebarModule(buildSidebar(tree, structure))

  const total = countMarkdownFiles(websiteCourseRoot)
  console.log(`Synced course → website/course/ (${total} published page(s), AI-Agent curriculum).`)
}

main()
